export const SET_ERRORS = 'SET_ERRORS';
export const TOGGLE_USER_LOADING = 'TOGGLE_USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER'


export const CREATE_POST = 'CREATE_POST'
export const GET_POST = 'GET_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const TOGGLE_POST_LOADING = 'POST_LOADING'
export const RESET_POST = 'RESET_POST'

export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const TOGGLE_POSTS_LOADING = 'TOGGLE_POSTS_LOADING'
